server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_db
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect